# vikrees/custom-actions-repo/.github/workflows/generic-ci.yaml
name: Generic CI Workflow

on:
  workflow_call:
    inputs:
      tags:
        required: true
        type: string
      build-args:
        required: false
        type: string
      Dockerfile:
        required: false
        type: string
        
runs:
  using: "composite"
  steps:
    - name: Build Docker Image
      uses: vikrees/custom-actions-repo/build@main
    - name: push Docker Image
      uses: vikrees/custom-actions-repo/push@main
