name: Generic CI Workflow

on:
  workflow_call:
    inputs:
      tags:
        required: true
        type: string
      build-args:
        required: false
        type: string
      Dockerfile:
        required: false
        type: string
      password:
        description: 'Docker Personal Access Token'
        required: true
      username:
        description: 'Docker Hub Username'
        required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Set up environment variables
      run: |
       echo "APPLICATION_IMAGE=${{ inputs.username }}:${{ github.run_id }}.${{ github.run_number }}.${{ github.run_attempt }}" >> $GITHUB_ENV
      shell: bash

    - name: Build Docker Image
      uses: vikrees/custom-actions-repo/build@main
      with:
        tags: ${{ inputs.tags }}
        Dockerfile: ${{ inputs.Dockerfile }}
        build-args: ${{ inputs.build-args }}
    - name: Push Docker Image
      uses: vikrees/custom-actions-repo/push@main
      with:
        tags: ${{ inputs.tags }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
