name: Generic CI Workflow

on:
  workflow_call:
    inputs:
      tags:
        required: true
        type: string
      build-args:
        required: false
        type: string
      Dockerfile:
        required: false
        type: string
      docker_pat:
        description: 'Docker Personal Access Token'
        required: true
      docker_username:
        description: 'Docker Hub Username'
        required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Build Docker Image
      uses: vikrees/custom-actions-repo/build@main
      with:
        tags: ${{ inputs.tags }}
        Dockerfile: ${{ inputs.Dockerfile }}
        build-args: ${{ inputs.build-args }}
    - name: Push Docker Image
      uses: vikrees/custom-actions-repo/push@main
      with:
        tags: ${{ inputs.tags }}
        username: ${{ input.docker_username }}
        password: ${{ input.docker_pat }}
