name: Generic CI Workflow

on:
  workflow_call:
    inputs:
      tags:
        required: true
        type: string
      build-args:
        required: false
        type: string
      Dockerfile:
        required: false
        type: string

runs:
  using: "composite"
  steps:
    - name: Build Docker Image
      uses: ./build/action.yml
      with:
        tags: ${{ inputs.tags }}
        Dockerfile: ${{ inputs.Dockerfile }}
        build-args: ${{ inputs.build-args }}
    - name: Push Docker Image
      uses: ./push/action.yml
      with:
        tags: ${{ inputs.tags }}