name: Push Docker Image
description: Push the Docker image

inputs:
  tags:
    description: 'Tags for the Docker image'
    required: true
  DOCKER_PAT:
    description: 'Docker Personal Access Token'
    required: true
  DOCKER_USERNAME:
    description: 'Docker Hub Username'
    required: true
    
runs:
  using: "composite"
  steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      run: echo "${{ inputs.docker_pat }}" | docker login -u ${{ inputs.docker_username }} --password-stdin
      shell: bash

    - name: Push app image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ inputs.tags }}
