name: Push Docker Image
description: Push the Docker image

inputs:
  tags:
    description: 'Tags for the Docker image'
    required: true
  docker_pat:
    description: 'Docker Personal Access Token'
    required: true
  docker_username:
    description: 'Docker Hub Username'
    required: true
    
runs:
  using: "composite"
  steps:
    - name: Check out the repository
      uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PAT }}

    - name: Push app image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ inputs.tags }}
