name: Push Docker Image
description: Push the Docker image

inputs:
  tags:
    description: 'Tags for the Docker image'
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2

    - name: Push app image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ inputs.tags }}
