name: Push Docker Image
description: Push the Docker image

inputs:
  tags:
    description: 'Tags for the Docker image'
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PAT }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - name: Push app image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ inputs.tags }}
