name: Build Docker Image
description: Build the Docker image

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push app image
      run: docker push ${{ inputs.tags }}
