name: Push Docker Image
description: Push the Docker image

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2

    - name: Push app image
      uses: docker/build-push-action@v2
      with:
        push: True
        tags: ${{ inputs.tags }}
