name: Build Docker Image
description: Build the Docker image

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: echo Tuk46ret! | docker login -u vikree@gmail.com" --password-stdin

    - name: Push app image
      run: docker push ${{ inputs.tags }}
