name: Push Docker Image
description: Push the Docker image

inputs:
  tags:
    description: 'Tags for the Docker image'
    required: true
  password:
    description: 'Docker Personal Access Token'
    required: true
  username:
    description: 'Docker Hub Username'
    required: true
    
runs:
  using: "composite"
  steps:

    - name: Check out the repository
      uses: actions/checkout@v2
    - name: check env
      run: env
      shell: bash
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: Push app image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ inputs.tags }}
