# vikrees/custom-actions-repo/.github/workflows/generic-ci.yaml
name: Generic CI Workflow

on:
  workflow_call:
    inputs:
      tags:
        required: true
        type: string
      build-args:
        required: false
        type: string
      Dockerfile:
        required: false
        type: string
        

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker Image
        uses: ./steps/build_action.yml
        with:
          tags: ${{ inputs.tags }}
          Dockerfile: ${{ inputs.Dockerfile }}
          build-args: ${{ inputs.build-args }}
