# vikrees/custom-actions-repo/.github/workflows/generic-ci.yaml
name: Generic CI Workflow

on:
  workflow_call:
    inputs:
      tags:
        required: true
        type: string
      build-args:
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker Image
        uses: ./steps/build_action.yml
        with:
          tags: ${{ inputs.tags }}
          build-args: ${{ inputs.build-args }}

  push:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Push Docker Image
        uses: ./steps/push_action.yml@main

