name: Generic CI Workflow

on:
  workflow_call:
    inputs:
      tags:
        required: true
        type: string
      build-args:
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker Image
        uses: vikrees/custom-actions-repo/steps/build_action.yml@main


  push:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Push Docker Image
        uses: vikrees/custom-actions-repo/steps/push_action.yml@main

